name: openteach
channels:
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - pytorch=1.12
  - torchvision=0.13
  - pyyaml=6.0  

  - pip:
      - blosc==1.11.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.45.1
      - Flask
      - gevent
      - gunicorn
      - h5py==3.10.0
      - hydra-core==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - numpy==1.26.2
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.1.0
      - pybullet==3.2.6
      - pyparsing==3.1.1
      - pyrealsense2==2.54.2.5684
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - scipy==1.11.4
      - six==1.16.0
      - tqdm==4.66.1
      - tzdata==2023.3
      - zmq==0.0.0
      - ikpy
      - shapely
      - rospkg
      - IPython

