# Bounds to clip the wrist keypoint values
wrist_bounds:
  x:
    - -0.05
    - 0.39
  y:
    - 1.04
    - 1.40
  z: 
    - 0.30
    - 0.05

# Bounds to perform linear transformation on the kinova arm
robot_bounds:
    # x: 
    #   - -0.035
    #   - 0.1
    # y: 
    #   - -0.2
    #   - -0.11
    # z: 
    #   - 0.015 #0.1051
    #   - 0.1
    x: 
      - 0.7
      - 1.3
    y: 
      - 0.9
      - 1.5
    z: 
      - -0.3 #0.1051
      - 0.3

# Corresponding axes
corresponding_robot_axes:
  x: 'x'
  y: 'y'
  z: 'z'

# kinova_frame_realignment_matrix: [
#   0, 1, 0,
#   0, 0, 1,
#   -1, 0, 0
# ]

kinova_frame_realignment_matrix: [
  1, 0, 0,
  0, 1, 0,
  0, 0, 1
]

kinova_rotation_alignment_matrix: [
  0, 0, 0,
  0, 0, 0,
  0, 0, -1
]
# kinova_frame_realignment_matrix: [
#   0.00036, 2.178, 0, 2.178, -3.743, 0, 0.000, 0, -4.743
#  ]

# kinova_rotation_alignment_matrix: [
#   0, 0,  0,
#   0, 0,  0,
#   0, 0,  -1
# ]

